
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import customtkinter as ctk
from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\grace\Desktop\GitReVisit\ReVisit-faceattend\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = ctk.CTk()

window.geometry("745x550")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 550,
    width = 745,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    373.0,
    65.0,
    708.0,
    491.0,
    fill="#E6E6E6",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    185.0,
    175.0,
    image=image_image_1
)

button_1 = ctk.CTkButton(
    master=window,
    text="Submit",  # Added spaces for horizontal 'padding'
    command=lambda: print("Submit button clicked"),
    width=120,  # Adjusted width
    height=42,   # Adjusted height
    corner_radius=10,  # Optional: adjust the corner radius for rounded corners
    fg_color="#5B757A",
    hover_color="#719298",
    font=("Inter", 18, "bold")
)

button_1.place(
    x=479.0,
    y=400.0,
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    185.0, #left to right
    278.0,
    image=image_image_2
)

canvas.create_text(
    399.0,
    125.0,
    anchor="nw",
    text="Full Name:",
    fill="#5B757A",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    399.0,
    197.0,
    anchor="nw",
    text="User Name:",
    fill="#5B757A",
    font=("Inter SemiBold", 15 * -1)
)

canvas.create_text(
    399.0,
    269.0,
    anchor="nw",
    text="Password:",
    fill="#5B757A",
    font=("Inter SemiBold", 15 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    540.5,
    169.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=406.0,
    y=152.0,
    width=269.0,
    height=32.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    540.5,
    241.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=406.0,
    y=224.0,
    width=269.0,
    height=32.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    540.5,
    313.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0,
    show="*"  # This makes the password hidden
)
entry_3.place(
    x=406.0,
    y=296.0,
    width=269.0,
    height=32.0
)
window.resizable(False, False)
window.mainloop()
