
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import customtkinter as ctk
from pathlib import Path
import os

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\grace\Desktop\GitReVisit\ReVisit-faceattend\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = ctk.CTk()

window.geometry("745x550")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 550,
    width = 745,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    66.0,
    56.0,
    674.0,
    482.0,
    fill="#E6E6E6",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    372.0,
    112.0,
    image=image_image_1
)

button_1 = ctk.CTkButton(
    master=window,
    text="Log In",  # Added spaces for horizontal 'padding'
    command=lambda: print("Submit button clicked"),
    width=150,  # Adjusted width
    height=42,   # Adjusted height
    corner_radius=10,  # Optional: adjust the corner radius for rounded corners
    fg_color="#5B757A",
    hover_color="#719298",
    font=("Inter", 18, "bold")
)

button_1.place(
    x=310.0,
    y=307.0,
)

def open_personnel_register():
    window.destroy()  # This closes the current window
    os.system('python "C:\\Users\\grace\\Desktop\\GitReVisit\\ReVisit-faceattend\\personnel_register.py"')

button_2 = ctk.CTkButton(
    master=window,
    text="Register",
    command=open_personnel_register,  # Updated to use the function
    width=150,
    height=42,
    corner_radius=10,
    fg_color="#5B757A",
    hover_color="#719298",
    font=("Inter", 18, "bold")
)
button_2.place(x=310.0, y=365.0)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    370.0,
    204.0,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()
